# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "empytools"
version = "2025.04.11"
dependencies = [
  "numpy",
  "matplotlib",
]
