name: tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform:
          - ubuntu-latest
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2
    - name: Poetry install dependencies
      run: poetry install
    - name: Run Lint
      run: |
        poetry run pylint empytools
        poetry run ruff check empytools
        poetry run black --check --diff empytools
    - name: Run Pytest
      run: poetry run pytest --cov=empytools tests/
